### PR TITLE
Added Spell Animation

### LINKED ISSUE #22: Implement Lovelace Spell Animation
When the player opens the secret Lovelace Library door using the spell, the corresponding animation should play (player using wand/spell affecting world). The door should then be unlocked allowing the player to walk through.

### PR DESCRIPTION
**Pull request by MarvelProgramming**
-Updated doors such that they only open after the player has cast the spell on them
-Updated doors such that they stay opened after the first time
-Updated "handleSpells" to use new "useWand" script
-Fixed bug where doors would become interactable again if the player left the their scene and went back
-Added "spell_color" property that determines the color of the spell to be cast (red, yellow, green, blue, or purple). If an object is spellable and no "spell_color" is specified, it'll default to red
-Added "useWand" script which handles disabling/enabling player movement, playing the spell animation, and cleaning up the spell sprite
-Removed unneeded sparkle object from lovelacehallway door

For issue #22 

This PR relies on the [changes made to the wand object in twilioquest-base](https://github.com/TwilioQuest/twilioquest-base/pull/100)

### CODE REVIEW

**Comment by MarvelProgramming** [comment]
Here are examples of the spell animations in action. Let me know if there's anything that needs to be adjusted @rmkubik @nmadadair @kerrielake!

#### Unlocking a door
https://user-images.githubusercontent.com/51891409/206952898-cea9851a-73f1-4cb4-b5a9-2a6fd04cb3b2.mov

#### Red spell (up, right , down, left)
https://user-images.githubusercontent.com/51891409/206953879-b5b3ee74-6f7b-460d-bf8b-74c05adc8b7d.mov

#### Yellow spell (up, right , down, left)
https://user-images.githubusercontent.com/51891409/206953940-fb4ba20b-c9e8-4ed5-8d2d-e0838b4653ac.mov

#### Green spell (up, right , down, left)
https://user-images.githubusercontent.com/51891409/206953978-6a2cf491-9972-4146-a6b6-0f6282d1e6ba.mov

#### Blue spell (up, right , down, left)
https://user-images.githubusercontent.com/51891409/206954040-04b46cce-248a-4986-b2cc-2e76081bc9ef.mov

#### Purple spell (up, right , down, left)
https://user-images.githubusercontent.com/51891409/206954080-ef66a87a-2980-4c1f-a712-6d0d2830c20c.mov

**Comment by nmadadair** [comment]
@MarvJohnson These spell animations are absolutely amazing!!! Really well done. So is the blue spell animation playing when the player opens the door? 

My only comment -- and maybe it's fine like this -- is about whether we want the blue spell marker to stay behind or in front of the player as they walk through the door? If we keep it as is, it's kind of like the magical spell is wafting over the player / they are entering through it. What do you think?

With these differently colored spells, we have so many opportunities to have the player interact with the world going forward. The idea for each of these spells was always that each one would open the secret doors AND ALSO interact with other spellable colors. So this is very exciting!

**Comment by MarvelProgramming** [comment]
> So is the blue spell animation playing when the player opens the door?

It is! It's just really hard to see because of the sparkle animation

> My only comment -- and maybe it's fine like this -- is about whether we want the blue spell marker to stay behind or in front of the player as they walk through the door? If we keep it as is, it's kind of like the magical spell is wafting over the player / they are entering through it. What do you think?

Is the "blue spell marker" the sparkle in this case? If so, it might be best to hide it immediately after the player interacts with the object associated with it. That way, the spell the player casts has greater visibility and we avoid any possible confusion in the future

**Comment by nmadadair** [comment]
> > So is the blue spell animation playing when the player opens the door?
> 
> It is! It's just really hard to see because of the sparkle animation
> 
> > My only comment -- and maybe it's fine like this -- is about whether we want the blue spell marker to stay behind or in front of the player as they walk through the door? If we keep it as is, it's kind of like the magical spell is wafting over the player / they are entering through it. What do you think?
> 
> Is the "blue spell marker" the sparkle in this case? If so, it might be best to hide it immediately after the player interacts with the object associated with it. That way, the spell the player casts has greater visibility and we avoid any possible confusion in the future

That makes a lot of sense to me!

**Comment by kerrielake** [comment]
@MarvJohnson I think removing the sparkle before the spell plays out is a great suggestion!

**Review by rmkubik — APPROVED** [review]

**Pull request merged**
